"""Generate src/forwards.h from the original steam_api64.dll.

Every export is forwarded to steam_api64_real.dll, except the few the proxy
implements itself (listed in OWN_EXPORTS).

Usage: python tools/gen_forwards.py path/to/original/steam_api64.dll
"""
import struct
import sys
from pathlib import Path

OWN_EXPORTS = {"SteamAPI_Shutdown"}
REAL_MODULE = "steam_api64_real"


def read_exports(path):
    data = Path(path).read_bytes()
    pe = struct.unpack_from("<I", data, 0x3C)[0]
    assert data[pe:pe + 4] == b"PE\0\0", "not a PE file"
    num_sections = struct.unpack_from("<H", data, pe + 6)[0]
    opt_size = struct.unpack_from("<H", data, pe + 20)[0]
    opt = pe + 24
    assert struct.unpack_from("<H", data, opt)[0] == 0x20B, "expected a 64-bit DLL"
    export_rva = struct.unpack_from("<I", data, opt + 112)[0]

    sections = []
    sec = opt + opt_size
    for i in range(num_sections):
        vsize, va, rawsize, rawptr = struct.unpack_from("<IIII", data, sec + i * 40 + 8)
        sections.append((va, max(vsize, rawsize), rawptr))

    def off(rva):
        for va, size, rawptr in sections:
            if va <= rva < va + size:
                return rva - va + rawptr
        raise ValueError(hex(rva))

    e = off(export_rva)
    base, nfuncs, nnames, _funcs, names, ords = struct.unpack_from("<IIIIII", data, e + 16)
    out = []
    for i in range(nnames):
        name_rva = struct.unpack_from("<I", data, off(names) + i * 4)[0]
        idx = struct.unpack_from("<H", data, off(ords) + i * 2)[0]
        n = off(name_rva)
        name = data[n:data.index(b"\0", n)].decode()
        out.append((base + idx, name))
    return sorted(out)


def main():
    exports = read_exports(sys.argv[1])
    lines = ["// Generated by tools/gen_forwards.py - do not edit by hand.", "#pragma once"]
    for ordinal, name in exports:
        if name not in OWN_EXPORTS:
            lines.append(f'#pragma comment(linker, "/export:{name}={REAL_MODULE}.{name},@{ordinal}")')
    dest = Path(__file__).resolve().parent.parent / "src" / "forwards.h"
    dest.write_text("\n".join(lines) + "\n")
    print(f"wrote {len(exports)} exports to {dest}")


if __name__ == "__main__":
    main()
